# Generated by Django 5.0.2 on 2026-03-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_destination'),
        ('destinations', '0003_guideservice_hotel_tourpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='destinations.guideservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='destinations.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='destinations.tourpackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('guide', 'Guide')], max_length=20),
        ),
    ]
