# Generated by Django 5.0.2 on 2026-03-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_guide_service_booking_hotel_booking_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('guide', 'Guide')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
