# Generated by Django 5.0.2 on 2026-03-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_guideservice_hotel_tourpackage'),
        ('reviews', '0003_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guide_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.guideservice'),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.tourpackage'),
        ),
    ]
