# Generated by Django 5.0.2 on 2026-03-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_destination'),
        ('destinations', '0001_initial'),
        ('reviews', '0003_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
