# Generated by Django 5.0.2 on 2026-03-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_guideservice_hotel_tourpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
