# Generated by Django 5.0.2 on 2026-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenlocation',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
