# Generated by Django 5.0.2 on 2026-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('traveler', 'Traveler'), ('business', 'Business Owner'), ('admin', 'Admin'), ('provider', 'Service Provider')], max_length=20, null=True),
        ),
    ]
